# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0434\u043d\u0435\u0439')),
                ('low_season', models.IntegerField(verbose_name='\u041d\u0438\u043a\u043a\u0438\u0439 \u0441\u0435\u0437\u043e\u043d')),
            ],
        ),
    ]
