# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skipass', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abonement',
            options={'verbose_name': '\u0414\u043d\u0438', 'verbose_name_plural': '\u0414\u043d\u0438'},
        ),
    ]
