# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skipass', '0006_auto_20160628_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=258, verbose_name='\u0418\u043c\u044f \u0441\u0435\u0437\u043e\u043d\u0430')),
                ('active', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u0410\u043a\u0442\u0438\u0432\u0435\u043d')),
                ('not_active', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u041d\u0435 \u0430\u043a\u0442\u0438\u0432\u0435\u043d')),
                ('days', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u0414\u043d\u0438')),
            ],
            options={
                'verbose_name': '\u0421\u0435\u0437\u043e\u043d',
                'verbose_name_plural': '\u0421\u0435\u0437\u043e\u043d\u044b',
            },
        ),
    ]
