# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skipass', '0007_seasons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonement',
            name='hi_season',
        ),
        migrations.RemoveField(
            model_name='abonement',
            name='low_season',
        ),
        migrations.AddField(
            model_name='abonement',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skipass.Seasons', verbose_name='C\u0435\u0437\u043e\u043d'),
        ),
    ]
