# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skipass', '0008_auto_20160722_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasons',
            name='days',
        ),
        migrations.AddField(
            model_name='abonement',
            name='price',
            field=models.IntegerField(null=True, verbose_name='\u0412 \u043a\u0430\u0441\u0441\u0430\u0445 \u0411\u0443\u043a\u043e\u0432\u0435\u043b\u044f'),
        ),
    ]
