# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skipass', '0009_auto_20160722_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonement',
            name='price',
            field=models.IntegerField(null=True, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
    ]
