# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-23 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skipass', '0011_auto_20160722_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abonement',
            old_name='bukovel_price',
            new_name='bukovel_price1',
        ),
        migrations.RenameField(
            model_name='abonement',
            old_name='price',
            new_name='price1',
        ),
        migrations.RemoveField(
            model_name='abonement',
            name='season',
        ),
        migrations.AddField(
            model_name='abonement',
            name='bukovel_price2',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0412 \u043a\u0430\u0441\u0441\u0430\u0445 \u0411\u0443\u043a\u043e\u0432\u0435\u043b\u044f'),
        ),
        migrations.AddField(
            model_name='abonement',
            name='price2',
            field=models.IntegerField(null=True, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
        migrations.AddField(
            model_name='abonement',
            name='season1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_1', to='skipass.Seasons', verbose_name='C\u0435\u0437\u043e\u043d'),
        ),
        migrations.AddField(
            model_name='abonement',
            name='season2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_2', to='skipass.Seasons', verbose_name='C\u0435\u0437\u043e\u043d'),
        ),
        migrations.AlterField(
            model_name='abonement',
            name='name',
            field=models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0434\u043d\u0435\u0439'),
        ),
    ]
