# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-27 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skipass', '0012_auto_20160723_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_title', models.CharField(max_length=200, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0430\u043a\u0446\u0438\u0438')),
                ('promo_text', models.TextField(null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0430\u043a\u0446\u0438\u0438')),
                ('promo_image', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('promo_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': '\u0410\u043a\u0446\u0438\u044f',
                'verbose_name_plural': '\u0410\u043a\u0446\u0438\u0438',
            },
        ),
    ]
