# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-03 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skipass', '0013_promo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubCartBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True, verbose_name='\u0418\u043c\u044f \u043a\u0430\u0440\u0442\u044b')),
                ('new', models.IntegerField(null=True, verbose_name='\u041d\u043e\u0432\u0430\u044f')),
                ('cont', models.IntegerField(null=True, verbose_name='\u041f\u0440\u043e\u0434\u043b\u0435\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u041a\u043b\u0443\u0431\u043d\u044b\u0435 \u043a\u0430\u0440\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='ClubCartBuyDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u044f')),
                ('clubcartbuy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skipass.ClubCartBuy')),
            ],
            options={
                'verbose_name': '\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043a\u043b\u0443\u0431\u043d\u044b\u0445 \u043a\u0430\u0440\u0442',
            },
        ),
        migrations.CreateModel(
            name='ClubCartPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u0418\u043c\u044f \u043a\u0430\u0440\u0442\u044b')),
                ('days', models.IntegerField(blank=True, verbose_name='\u0414\u043d\u0438')),
                ('price', models.IntegerField(blank=True, verbose_name='\u0426\u0435\u043d\u0430')),
                ('active', models.CharField(max_length=256, null=True, verbose_name='\u0410\u043a\u0442\u0438\u0432\u0435\u043d')),
                ('not_active', models.CharField(max_length=256, null=True, verbose_name='\u041d\u0435 \u0430\u043a\u0442\u0438\u0432\u0435\u043d')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u0435 \u043a\u0430\u0440\u0442',
            },
        ),
    ]
