# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-03 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skipass', '0014_clubcartbuy_clubcartbuydesc_clubcartpay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubcartpay',
            name='name',
        ),
    ]
