# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-03 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skipass', '0015_remove_clubcartpay_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abonement',
            options={'verbose_name': '\u0421\u043a\u0438\u043f\u0430\u0441\u0441', 'verbose_name_plural': '\u0421\u043a\u0438\u043f\u0430\u0441\u0441\u044b'},
        ),
    ]
