# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-04 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skipass', '0016_auto_20160903_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubcartpay',
            name='active',
        ),
        migrations.RemoveField(
            model_name='clubcartpay',
            name='not_active',
        ),
        migrations.AddField(
            model_name='clubcartpay',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season', to='skipass.Seasons', verbose_name='C\u0435\u0437\u043e\u043d'),
        ),
    ]
