# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skipass', '0018_qa'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.CharField(max_length=128, verbose_name='\u041f\u043e\u0447\u0442\u043e\u0432\u044b\u0439 \u0430\u0434\u0440\u0435\u0441 \u0430\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440\u0430')),
                ('host', models.CharField(max_length=128, verbose_name='\u0430\u0434\u0440\u0435\u0441 SMTP')),
                ('port', models.IntegerField(max_length=8, verbose_name='\u041f\u043e\u0440\u0442')),
                ('user', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u0418\u043c\u044f \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u041f\u0430\u0440\u043e\u043b\u044c')),
                ('tls', models.BooleanField(default=False, verbose_name='TLS')),
                ('ssl', models.BooleanField(default=False, verbose_name='SSL')),
            ],
        ),
        migrations.AlterModelOptions(
            name='clubcartbuy',
            options={'verbose_name': '\u041a\u043b\u0443\u0431\u043d\u044b\u0435 \u043a\u0430\u0440\u0442\u044b', 'verbose_name_plural': '\u041a\u043b\u0443\u0431\u043d\u044b\u0435 \u043a\u0430\u0440\u0442\u044b'},
        ),
        migrations.AlterModelOptions(
            name='clubcartpay',
            options={'verbose_name': '\u041f\u043e\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u0435 \u043a\u0430\u0440\u0442', 'verbose_name_plural': '\u041f\u043e\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u0435 \u043a\u0430\u0440\u0442'},
        ),
        migrations.AlterModelOptions(
            name='qa',
            options={'verbose_name': '\u0412\u043e\u043f\u0440\u043e\u0441\u044b \u0438 \u043e\u0442\u0432\u0435\u0442\u044b', 'verbose_name_plural': '\u0412\u043e\u043f\u0440\u043e\u0441\u044b \u0438 \u043e\u0442\u0432\u0435\u0442\u044b'},
        ),
    ]
