# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skipass', '0019_auto_20160908_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smtp',
            options={'verbose_name': '\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0430 \u043f\u043e\u0447\u0442\u044b', 'verbose_name_plural': '\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0430 \u043f\u043e\u0447\u0442\u044b'},
        ),
    ]
