# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-12 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skipass', '0020_auto_20160908_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonementHight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0434\u043d\u0435\u0439')),
                ('price', models.IntegerField(null=True, verbose_name='\u0426\u0435\u043d\u0430')),
                ('bukovel_price', models.IntegerField(blank=True, null=True, verbose_name='\u0412 \u043a\u0430\u0441\u0441\u0430\u0445 \u0411\u0443\u043a\u043e\u0432\u0435\u043b\u044f')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_hight', to='skipass.Seasons', verbose_name='C\u0435\u0437\u043e\u043d')),
            ],
            options={
                'verbose_name': '\u0421\u043a\u0438\u043f\u0430\u0441\u0441 - \u0432\u044b\u0441\u043e\u043a\u0439\u0438',
                'verbose_name_plural': '\u0421\u043a\u0438\u043f\u0430\u0441\u0441\u044b - \u0432\u044b\u0441\u043e\u043a\u0438\u0439',
            },
        ),
        migrations.CreateModel(
            name='AbonementLow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0434\u043d\u0435\u0439')),
                ('price', models.IntegerField(null=True, verbose_name='\u0426\u0435\u043d\u0430')),
                ('bukovel_price', models.IntegerField(blank=True, null=True, verbose_name='\u0412 \u043a\u0430\u0441\u0441\u0430\u0445 \u0411\u0443\u043a\u043e\u0432\u0435\u043b\u044f')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_low', to='skipass.Seasons', verbose_name='C\u0435\u0437\u043e\u043d')),
            ],
            options={
                'verbose_name': '\u0421\u043a\u0438\u043f\u0430\u0441\u0441 - \u043d\u0438\u0437\u043a\u0438\u0439',
                'verbose_name_plural': '\u0421\u043a\u0438\u043f\u0430\u0441\u0441\u044b - \u043d\u0438\u0437\u043a\u0438\u0439',
            },
        ),
        migrations.RemoveField(
            model_name='abonement',
            name='season1',
        ),
        migrations.RemoveField(
            model_name='abonement',
            name='season2',
        ),
        migrations.AlterField(
            model_name='smtp',
            name='port',
            field=models.IntegerField(verbose_name='\u041f\u043e\u0440\u0442'),
        ),
        migrations.DeleteModel(
            name='Abonement',
        ),
    ]
