# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-12 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skipass', '0023_abonementlow_desc_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='smtp',
            unique_together=set([('ssl', 'tls')]),
        ),
    ]
