# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-13 10:48
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('skipass', '0027_promo_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='content',
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_text',
            field=tinymce.models.HTMLField(null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0430\u043a\u0446\u0438\u0438'),
        ),
    ]
