# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-14 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skipass', '0029_auto_20160914_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promo',
            old_name='promo_text',
            new_name='text',
        ),
    ]
