# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-19 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skipass', '0030_auto_20160914_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='season_promo', to='skipass.Seasons', verbose_name='C\u0435\u0437\u043e\u043d'),
        ),
    ]
